# Generated by Django 6.1.1 on 2026-09-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHi0HDEC4AHKzvFurHhnfMY73FYok-UY0rlgvl3f0gfg&s=10')),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='Not provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
